/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.app.paginas.contratos;

import com.app.pdfs.PDFGenerator;
import com.app.util.FilePath;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class PerdaCartao extends javax.swing.JInternalFrame {

    /**
     * Creates new form PerdaCartao
     */
    public PerdaCartao() {
        initComponents();
        setTitle("Gerar CARTA COMUNICANDO PERDA DE CARTÃO DE CRÉDITO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtContratante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtContratado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMotivo = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jtAssinoCartao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtPerdaCartao = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbGerar = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();

        jLabel1.setText("Contratante");

        jtContratante.setText("jTextField1");

        jLabel2.setText("Contratado");

        jtContratado.setText("jTextField2");

        jLabel3.setText("Motivo");

        jtMotivo.setColumns(20);
        jtMotivo.setLineWrap(true);
        jtMotivo.setRows(5);
        jScrollPane1.setViewportView(jtMotivo);

        jLabel4.setText("Data de assino do Cartão");

        jtAssinoCartao.setText("jTextField3");

        jLabel5.setText("Data Perda Cartão");

        jbGerar.setText("Gerar");
        jbGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGerar)
                .addGap(27, 27, 27)
                .addComponent(jbFechar)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGerar)
                    .addComponent(jbFechar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jtAssinoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtPerdaCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtContratado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addComponent(jtContratante, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtContratante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(jtContratado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAssinoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPerdaCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarActionPerformed
       
        
        try {
            PDFGenerator pdfg = new PDFGenerator();
            pdfg.setInputFilePath("contract_tampletes/CARTA COMUNICANDO PERDA DE CARTÃO DE CRÉDITO.doc");
            
            pdfg.openWord();
            pdfg.modifyWord("CONTRATANTE", jtContratante.getText());
            pdfg.modifyWord("CONTRATADO", jtContratado.getText());
            pdfg.modifyWord("Em (xxx)", String.format("Em %s", jtAssinoCartao.getText()));
            pdfg.modifyWord("no dia (xxx)", String.format("no dia %s", jtPerdaCartao.getText()));
            
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES); // Permitir apenas seleção de diretórios
            fileChooser.setDialogTitle("Escolha um diretório para salvar");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos PDF", "pdf");
            fileChooser.setFileFilter(filter);

            int returnValue = fileChooser.showSaveDialog(null); // Exibir o diálogo de seleção de arquivo para salvar

            if (returnValue == JFileChooser.APPROVE_OPTION) {
                String selectedDirectory = fileChooser.getSelectedFile().getAbsolutePath();
                if(!selectedDirectory.endsWith(".doc")) {
                    selectedDirectory += ".doc";
                    
                }
                pdfg.setOutputFilePath(selectedDirectory);
            } else {
                throw new IOException("Caminho não especificado");
            }
            pdfg.close();
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        /*
        
        try {
            GeneratePDF generatePDF = new GeneratePDF(
                FilePath.getPath("contract_tampletes/CARTA COMUNICANDO PERDA DE CARTÃO DE CRÉDITO.doc"),
                FilePath.getPath("final/t.doc"));
            if(jtMotivo.getText().isEmpty() || jtMotivo.getText() == null) {
                throw new IllegalArgumentException("Campo motivo está vazio");
            }
            generatePDF.openWord();
            generatePDF.modifyWord("CONTRATANTE", jtContratante.getText());
            generatePDF.modifyWord("CONTRATADO", jtContratado.getText());
            generatePDF.modifyWord(
                    "(xxx) (Descrever as circunstâncias em que se deu a perda, indicando a existência de documento comprovando).",
                    jtMotivo.getText());
            generatePDF.modifyWord("Em (xxx)", String.format("Em %s", jtAssinoCartao.getText()));
            generatePDF.modifyWord("no dia (xxx)", String.format("no dia %s", jtAssinoCartao.getText()));
            generatePDF.saveWord();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (IllegalArgumentException e){
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
        */
    }//GEN-LAST:event_jbGerarActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbGerar;
    private javax.swing.JTextField jtAssinoCartao;
    private javax.swing.JTextField jtContratado;
    private javax.swing.JTextField jtContratante;
    private javax.swing.JTextArea jtMotivo;
    private javax.swing.JTextField jtPerdaCartao;
    // End of variables declaration//GEN-END:variables
}
